### ISSUE TITLE
[Feat] view 작업

### ISSUE THREAD

**Issue by yong313** [yong313/wanted-codestates-project-10#1]
### TODO
 - [ ] 헤더 view 작업
 - [ ] 컨텐츠 view 작업
 - [ ] 푸터 view 작업
